// Generated by CoffeeScript 1.6.2
define(['pages/draw.view', 'pages/home.view', 'models/app.model'], function(DrawView, HomeView, AppModel) {
  var App;

  App = Backbone.Router.extend({
    routes: {
      '': 'showHome',
      'draw': 'showDraw'
    },
    initialize: function(options) {
      this.model = new AppModel();
      this.$el = $('body');
      return Backbone.history.start();
    },
    showHome: function() {
      return this.showPage(HomeView);
    },
    showDraw: function() {
      return this.showPage(DrawView);
    },
    showPage: function(Page) {
      var _ref;

      if ((_ref = this.curView) != null) {
        if (typeof _ref.remove === "function") {
          _ref.remove();
        }
      }
      this.curView = new Page({
        'app': this.model
      });
      return this.$el.html(this.curView.render().el);
    }
  });
  return App;
});
