// Generated by CoffeeScript 1.6.2
define(['./colorPicker.tmpl.html'], function(tmpl) {
  var View;

  return View = Backbone.View.extend({
    template: _.template(tmpl),
    initialize: function() {},
    render: function() {
      this.el.html(this.template());
      return this;
    }
  });
});
