// Generated by CoffeeScript 1.6.2
define(["text!./draw.tmpl.html"], function(tmpl) {
  var Page;

  Page = Backbone.View.extend({
    className: 'drawPage',
    events: {
      'click .shapePicker .pickSquare': 'onSquareClicked',
      'click .shapePicker .pickCircle': 'onCircleClicked'
    },
    template: _.template(tmpl),
    initialize: function() {
      this.model = this.options.app;
      return this.listenTo(this.model, 'change', this.render);
    },
    render: function() {
      this.$el.html(this.template(this.model.attributes));
      return this;
    },
    onSquareClicked: function() {
      return this.options.app.set('curShape', this.options.app.shapes.SQUARE);
    },
    onCircleClicked: function() {
      return this.options.app.set('curShape', this.options.app.shapes.CIRCLE);
    }
  });
  return Page;
});
