// Generated by CoffeeScript 1.6.2
define(['text!./draw.tmpl.html', 'views/shapePicker.view', 'views/colorPicker.view'], function(tmpl, ShapePicker, ColorPicker) {
  var Page;

  Page = Backbone.View.extend({
    className: 'drawPage',
    template: _.template(tmpl),
    initialize: function() {
      this.model = this.options.app;
      return this.listenTo(this.model, 'change', this.render);
    },
    render: function() {
      var $Pickers;

      this.$el.html(this.template(this.model.attributes));
      this.pickShape = new ShapePicker({
        'app': this.options.app
      });
      this.pickColor = new ColorPicker({
        'app': this.options.app
      });
      $Pickers = this.$('#Pickers');
      $Pickers.append(this.pickColor.render().el);
      $Pickers.append(this.pickShape.render().el);
      return this;
    }
  });
  return Page;
});
