// Generated by CoffeeScript 1.6.2
define(["text!./home.tmpl.html"], function(tmpl) {
  var Page;

  Page = Backbone.View.extend({
    className: 'homePage',
    template: _.template(tmpl),
    initialize: function() {},
    render: function() {
      this.$el.html(this.template());
      return this;
    }
  });
  return Page;
});
