// Generated by CoffeeScript 1.6.2
define(['./shape.model'], function(ShapeModel) {
  var Model;

  Model = Backbone.Model.extend({
    defaults: function() {
      return {
        'curShape': ShapeModel.shapes.SQUARE,
        'curColor': ShapeModel.colors[1]
      };
    },
    initialize: function() {
      this.colors = ShapeModel.colors;
      return this.shapes = ShapeModel.shapes;
    }
  });
  return Model;
});
