// Generated by CoffeeScript 1.6.2
define([], function() {
  var Model;

  Model = Backbone.Model.extend({
    defaults: {
      zIndex: 0,
      posX: 0,
      posY: 0,
      width: 100,
      height: 100
    },
    initialize: function() {}
  });
  Model.colors = ['#FDEDD0', '#BCF1ED', '#FF634D', '#FD795B', '#FFF0AA'];
  Model.shapes = {
    'SQUARE': 'square',
    'CIRCLE': 'circle'
  };
  return Model;
});
